format = "($cmd_duration)\n╭─$username@$hostname(\n│ $directory)(\n│ $git_branch)(\n│ $nix_shell)\n╰─[❯❯❯](red) "

[username]
show_always = true
style_user = 'bold bright-yellow'
style_root = 'bold red'
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'
style = 'bold green'

[directory]
style = 'bold bright-cyan'
truncation_symbol = '../'
truncate_to_repo = false
format = '[$read_only]($read_only_style)[ $path]($style)'
read_only = ' '

[git_branch]
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '

[nix_shell]
disabled = false
symbol = '❄️'
style = 'bold'
format = 'via [$symbol $name]($style)'

[cmd_duration]
min_time = 1_000
show_notifications = true
min_time_to_notify = 60_000
format = '⏱️ [$duration](black)'
